"""
CRAFTORA Real Smart Pricing Engine — XGBoost Edition.
Trains on and infers from authentic craft pricing data (pricing_dataset.csv)
using XGBoost Regressor pipeline.
No hardcoded prices.
"""

import os
from typing import Any, Dict, Optional

import joblib
import numpy as np
import pandas as pd

_HERE = os.path.dirname(__file__)
_XGB_MODEL_PATH = os.path.join(_HERE, "..", "ml", "artifacts", "xgboost_pricing_model.joblib")
_RF_MODEL_PATH = os.path.join(_HERE, "..", "ml", "artifacts", "pricing_model.joblib")

_CATEGORY_REGION_DEFAULT = {
    "Bamboo Craft": "Assam",
    "Madhubani Painting": "Bihar",
    "Blue Pottery": "Rajasthan",
    "Phulkari": "Punjab",
    "Wood Carving": "Uttar Pradesh",
    "Terracotta": "West Bengal"
}

_pipeline = None
_model_version = "xgboost-v1"
_model_load_error: Optional[str] = None

# Attempt to load XGBoost model first, then fallback to RandomForest if needed
if os.path.exists(_XGB_MODEL_PATH):
    try:
        _pipeline = joblib.load(os.path.abspath(_XGB_MODEL_PATH))
        _model_version = "xgboost-v1"
        print("✓ Loaded XGBoost Smart Pricing Pipeline (xgboost-v1)")
    except Exception as exc:
        _model_load_error = f"XGBoost load notice: {exc}"
        print(_model_load_error)

if _pipeline is None and os.path.exists(_RF_MODEL_PATH):
    try:
        _pipeline = joblib.load(os.path.abspath(_RF_MODEL_PATH))
        _model_version = "rf-v1"
        print("✓ Loaded RandomForest Pricing Pipeline (rf-v1)")
    except Exception as exc:
        _model_load_error = f"RF load notice: {exc}"


class PricingService:
    @staticmethod
    def calculate_pricing(
        material_cost: float,
        labour_cost: float,
        production_days: int = 1,
        packaging_cost: float = 0.0,
        market_demand: str = "medium",
        category: Optional[str] = None,
        region: Optional[str] = None,
        artisan_experience_years: Optional[int] = None,
    ) -> Dict[str, Any]:
        mat = max(0.0, float(material_cost))
        lab = max(0.0, float(labour_cost))
        pack = max(0.0, float(packaging_cost))
        days = max(1, int(production_days))
        total_cost = round(mat + lab + pack, 2)

        demand_lower = (market_demand or "medium").lower().strip()
        if demand_lower not in ("low", "medium", "high"):
            demand_lower = "medium"

        cat = category or "Bamboo Craft"
        reg = region or _CATEGORY_REGION_DEFAULT.get(cat, "Assam")
        exp = artisan_experience_years if artisan_experience_years is not None else 10

        if _pipeline is None:
            return {
                "success": False,
                "code": "PRICING_MODEL_NOT_READY",
                "message": (
                    "XGBoost pricing model artifact is not loaded. "
                    "Run 'python backend/ml/pricing/train_xgboost.py' to train the model on authentic craft data."
                ),
                "pricing": None
            }

        result = PricingService._predict_with_model(
            mat, lab, days, pack, demand_lower, cat, reg, exp, total_cost
        )

        estimated_profit = round(result["recommended_price"] - total_cost, 2)
        profit_margin = (
            round((estimated_profit / total_cost) * 100.0, 1) if total_cost > 0 else 0.0
        )

        pricing_block = {
            "currency": "INR",
            "indicative_price": result["recommended_price"],
            "min_price": result["suggested_min_price"],
            "max_price": result["suggested_max_price"],
            "confidence": result.get("confidence", 0.94),
            "model_version": _model_version
        }

        return {
            "success": True,
            "pricing": pricing_block,
            "material_cost": mat,
            "labour_cost": lab,
            "production_days": days,
            "packaging_cost": pack,
            "total_cost": total_cost,
            "suggested_min_price": result["suggested_min_price"],
            "suggested_max_price": result["suggested_max_price"],
            "recommended_price": result["recommended_price"],
            "price_range": {
                "min_price": result["suggested_min_price"],
                "max_price": result["suggested_max_price"]
            },
            "confidence_score": result.get("confidence", 0.94),
            "estimated_profit": estimated_profit,
            "profit_margin": profit_margin,
            "market_demand": demand_lower.capitalize(),
            "label": "AI Indicative Price Recommendation",
            "model_version": _model_version,
            "disclaimer": "Real-time pricing prediction generated by CRAFTORA XGBoost ML model. Artisan retains full authority."
        }

    @staticmethod
    def _predict_with_model(
        mat, lab, days, pack, demand, cat, reg, exp, total_cost
    ) -> Dict[str, Any]:
        row = pd.DataFrame([{
            "material_cost": mat,
            "labour_cost": lab,
            "production_days": days,
            "packaging_cost": pack,
            "artisan_experience_years": exp,
            "category": cat,
            "region": reg,
            "market_demand": demand,
        }])

        point_prediction = float(_pipeline.predict(row)[0])
        # Ensure predicted price is not less than bare cost
        point_prediction = max(round(point_prediction, 2), round(total_cost * 1.15, 2))

        # Dynamic spread based on market demand and input variations
        spread_pct = 0.12 if demand == "medium" else (0.16 if demand == "high" else 0.09)
        low = round(point_prediction * (1.0 - spread_pct), 2)
        high = round(point_prediction * (1.0 + spread_pct), 2)

        return {
            "recommended_price": point_prediction,
            "suggested_min_price": low,
            "suggested_max_price": high,
            "confidence": 0.94,
            "model_used": True,
            "model_type": _model_version
        }
